### ISSUE TITLE
mac os 下无法编译cpt

### ISSUE THREAD

**Issue by sxiaojian88** [xingetouzi/vnpy_fxdayu#10]
vnpy/api/cpt 目录下 执行  bash build.sh

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CTPAPI_MD_LIBRARY
    linked by target "vnctpmd" in directory ~/vnpy_fxdayu/vnpy/api/ctp
CTPAPI_TD_LIBRARY
    linked by target "vnctptd" in directory ~/vnpy_fxdayu/vnpy/api/ctp

-- Configuring incomplete, errors occurred!
See also "~/vnpy_fxdayu/vnpy/api/ctp/build/CMakeFiles/CMakeOutput.log".

**Comment by ukamoy** [comment]
暂时不支持MACOS编译，欢迎继续关注我们的更新
