### ISSUE TITLE
能否支持国内的股票交易?

### ISSUE THREAD

**Issue by zfsamzfsam** [xingetouzi/vnpy_fxdayu#23]
tdx_api
	python版trade.dll
	使用boost python对c++版的通达信接口进行包装，生成一个python版本的接口
	https://github.com/JaysonAlbert/tdx_api

rainx/TdxTradeServer
	TongDaXin Tarde Server 通达信交易服务器
	https://github.com/rainx/TdxTradeServer

富途开放API Python SDK
	https://github.com/FutunnOpen/py-futu-api

**Comment by BurdenBear** [comment]
项目主要针对数字货币、期货Ctp、Oanda，短期内没有对接A股的计划。
